apiVersion: apps/v1
kind: ReplicaSet
metadata: 
 name: nginx-rs
 labels:
   env: practice
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        env: practice
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
  replicas: 5
  selector:
    matchLabels:
       env: practice
     

